export const Colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#fff",
  COLOR_DARK: "#000",
  COLOR_DARK_ALT: "#262626",
};

// Data for food categories

export const Categories = [
    {
        id: "01",
        category: "Breakfast"
    },
    {
        id: "02",
        category: "Lunch"
    },
    {
        id: "03",
        category: "Dinner"
    },
];

export const Exercisecategories = [
  {
    id: "01",
    category: "Aerobic"
  },
  {
    id: "02",
    category: "Gait"
  },
  {
    id: "03",
    category: "Strength"
  }
];

export const Foods = [
    {
        id: "01",
        name: "Oatmeal",
        category: "Breakfast",
        image: require("../assets/images/oatmeal.jpg"),
        rating: "4.8",
        ingredients: ["Rolled oats", "Low-fat milk", "Mixed barries", "Nuts"],
        description: ["A hearty bowl of oatmeal topped with fresh berries and crunchy nuts for a nutritious start."],
        recipe: ["In a pot, bring water or milk to a boil.",
                 "Add oats, reduce heat, and simmer for 5-7 minutes, stirring occasionally.",
                 "Top with mixed berries and nuts.",
                 "Drizzle with honey or maple syrup if desired."],
        time: "15 mins",
        difficulty: "Easy",
        calories: "300 cal"
    },
    {
        id: "02",
        name: "Avocado Toast",
        category: "Breakfast",
        image: require("../assets/images/avocadotoast.jpg"),
        rating: "4.7",
        ingredients: ["Avocado", "Whole-grain bread", "Tomato", "Salt", "Pepper", "Lemon juice"],
        description: ["Creamy avocado spread on whole-grain toast with fresh tomato slices and a sprinkle of lemon juice."],
        recipe: ["Toast the whole-grain bread.",
                 "Mash the avocado and spread it on the toast.",
                 "Top with tomato slices.",
                 "Season with salt, pepper, and a squeeze of lemon juice.",
                 "Garnish with basil leaves if desired."
        ],
        time: "5 mins",
        difficulty: "Easy",
        calories: "250 cal"
    },
    {
        id: "03",
        name: "Greek Yogurt",
        category: "Breakfast",
        image: require("../assets/images/greekyogurt.jpg"),
        rating: "4.6",
        ingredients: ["Greek yogurt", "Honey", "Stawberries", "Berries", "Almonds"],
        description: ["A simple and satisfying bowl of Greek yogurt sweetened with honey and topped with crunchy nuts."],
        recipe: ["Spoon the Greek yogurt into a bowl.",
                 "Drizzle with honey.",
                 "Sprinkle with chopped nuts.",
                 "Garnish with fresh mint leaves if desired."
        ],
        time: "5 mins",
        difficulty: "Easy",
        calories: "220 cal"
    },
    {
        id: "04",
        name: "Vegetable Omelette",
        category: "Breakfast",
        image: require("../assets/images/vegetableomelette.jpg"),
        rating: "4.5",
        ingredients: ["2 Eggs", "Spinach", "Bell peppers", "Tomatoes", "Olive oil", "Salt", "Pepper"],
        description: ["A fluffy omelette packed with colorful vegetables for a protein-rich breakfast."],
        recipe: ["In a bowl, whisk the eggs with a pinch of salt and pepper.",
                 "Heat olive oil in a non-stick pan over medium heat.",
                 "Add the chopped vegetables and sauté for 2-3 minutes.",
                 "Pour the eggs over the vegetables and cook until set.",
                 "Fold the omelette in half and serve."
        ],
        time: "10 mins",
        difficulty: "Medium",
        calories: "200 cal"
    },
    {
        id: "05",
        name: "Smoothie Bowl",
        category: "Breakfast",
        image: require("../assets/images/smoothiebowl.jpg"),
        rating: "4.7",
        ingredients: ["Banana", "Berries", "Spinach", "Almond milk", "Chia seeds"],
        description: ["A vibrant smoothie bowl blended with fruits and topped with granola and fresh fruit slices."],
        recipe: ["Blend the banana, frozen berries, spinach, and almond milk until smooth.",
                 "Pour into a bowl.",
                 "Top with sliced fruit, granola, and shredded coconut."
        ],
        time: "5 mins",
        difficulty: "Easy",
        calories: "350 cal"
    },
    {
        id: "06",
        name: "Whole-Grain Pancakes",
        category: "Breakfast",
        image: require("../assets/images/pancakes.jpg"),
        rating: "4.6",
        ingredients: ["Whole-grain flour", "Baking powder", "Honey", "Low-fat milk", "Egg", "Olive oil", "Fruits"],
        description: ["Light and fluffy pancakes made with whole-grain flour, perfect for a healthy breakfast treat."],
        recipe: ["In a bowl, mix the flour and baking powder.",
                "In another bowl, whisk together the milk, egg, honey, and olive oil.",
                "Combine the wet and dry ingredients.",
                "Heat a non-stick pan and pour small amounts of batter to form pancakes.",
                "Cook until bubbles form, then flip and cook the other side.",
                "Serve with fresh fruit or yogurt."
        ],
        time: "20 mins",
        difficulty: "Medium",
        calories: "350 cal"
    },
    {
        id: "07",
        name: "Chia Seed Pudding",
        category: "Breakfast",
        image: require("../assets/images/chiaseedpudding.jpg"),
        rating: "4.7",
        ingredients: ["Chia seeds", "Almond milk", "Honey", "Vanilla extract", "Fruits"],
        description: ["A creamy and nutritious chia seed pudding that sets overnight, topped with fresh fruits."],
        recipe: ["In a bowl, mix the chia seeds, almond milk, honey, and vanilla extract.",
                 "Stir well to combine.",
                 "Cover and refrigerate for at least 2 hours, or overnight, until it reaches a pudding-like consistency.",
                 "Stir again before serving and top with fresh fruit."
        ],
        time: "10 mins",
        difficulty: "Easy",
        calories: "200 cal"
    },
    {
        id: "08",
        name: "Quinoa Breakfast Bowl",
        category: "Breakfast",
        image: require("../assets/images/quinoabreakfastbowl.jpg"),
        rating: "4.6",
        ingredients: ["Cooked quinoa", "Almond milk", "Honey", "Cinnamon", "Fresh barries", "Nuts"],
        description: ["A warm bowl of quinoa sweetened with honey and cinnamon, garnished with berries and nuts."],
        recipe: ["In a small saucepan, heat the cooked quinoa and almond milk over medium heat.",
                 "Stir in the honey and cinnamon.",
                 "Cook until heated through, about 3-5 minutes.",
                 "Transfer to a bowl and top with fresh berries and chopped nuts."
        ],
        time: "10 mins",
        difficulty: "Medium",
        calories: "350 cal"
    },
    {
        id: "09",
        name: "Grilled Chicken Salad",
        category: "Lunch",
        image: require("../assets/images/grilledchickensalad.jpg"),
        rating: 4.8,
        ingredients: ["Chicken breast", "Mixed greens", "Cherry tomatoes", "Cucumber", "Olive oil", "Lemon juice", "Salt", "Pepper"],
        description: ["A nutritious salad with grilled chicken, fresh greens, and a light vinaigrette."],
        recipe: ["Season chicken with salt and pepper, then grill until fully cooked.",
                 "In a bowl, mix greens, cherry tomatoes, and cucumber.",
                 "Slice grilled chicken and add to the salad.",
                 "Drizzle with olive oil and lemon juice."
        ],
        time: "20 mins",
        difficulty: "Easy",
        calories: "350 cal"    
    },
    {
        id: "10",
        name: "Quinoa and Black Bean Salad",
        category: "Lunch",
        image: require("../assets/images/quinoablackbeansalad.jpg"),
        rating: 4.7,
        ingredients: ["Quinoa", "Black beans", "Bell peppers", "Corn", "Cilantro", "Lime juice", "Olive oil", "Salt", "Pepper"],
        description: "A protein-packed salad with quinoa, black beans, and colorful veggies.",
        recipe: [
          "Cook quinoa according to package instructions.",
          "In a large bowl, mix cooked quinoa, black beans, diced bell peppers, and corn.",
          "Add chopped cilantro, lime juice, olive oil, salt, and pepper to taste."
        ],
        time: "25 mins",
        difficulty: "Easy",
        calories: "400 cal"
      },
      {
        id: "11",
        name: "Lentil Soup",
        category: "Lunch",
        image: require("../assets/images/lentilsoup.jpg"),
        rating: 4.6,
        ingredients: ["Lentils", "Carrots", "Celery", "Onion", "Garlic", "Vegetable broth", "Olive oil", "Salt", "Pepper", "Thyme"],
        description: "A hearty and warming lentil soup with vegetables.",
        recipe: [
          "Sauté chopped onions, carrots, celery, and garlic in olive oil.",
          "Add lentils, vegetable broth, salt, pepper, and thyme.",
          "Simmer until lentils are tender."
        ],
        time: "40 mins",
        difficulty: "Medium",
        calories: "300 cal"
      },
      {
        id: "12",
        name: "Turkey and Avocado Wrap",
        category: "Lunch",
        image: require("../assets/images/turkeyavocadowrap.jpg"),
        rating: 4.8,
        ingredients: ["Whole-grain tortilla", "Turkey slices", "Avocado", "Lettuce", "Tomato", "Mustard"],
        description: "A light and refreshing wrap with turkey, avocado, and veggies.",
        recipe: [
          "Spread mustard on the tortilla.",
          "Layer with turkey slices, avocado, lettuce, and tomato.",
          "Roll up and slice in half."
        ],
        time: "10 mins",
        difficulty: "Easy",
        calories: "350 cal"
      },
      {
        id: "13",
        name: "Salad Sandwich",
        category: "Lunch",
        image: require("../assets/images/chickpeasaladsandwich.jpg"),
        rating: 4.7,
        ingredients: ["Chickpeas", "Greek yogurt", "Lemon juice", "Celery", "Green onion", "Whole-grain bread", "Salt", "Pepper"],
        description: "A vegetarian sandwich with mashed chickpeas and fresh veggies.",
        recipe: [
          "Mash chickpeas with Greek yogurt and lemon juice.",
          "Mix in chopped celery and green onion.",
          "Season with salt and pepper.",
          "Spread on whole-grain bread."
        ],
        time: "15 mins",
        difficulty: "Easy",
        calories: "300 cal"
      },
      {
        id: "14",
        name: "Baked Salmon with Asparagus",
        category: "Lunch",
        image: require("../assets/images/bakedsalmonasparagus.jpg"),
        rating: 4.9,
        ingredients: ["Salmon fillet", "Asparagus", "Olive oil", "Lemon", "Garlic", "Salt", "Pepper"],
        description: "A heart-healthy dish with baked salmon and asparagus.",
        recipe: [
          "Preheat oven to 375°F (190°C).",
          "Place salmon and asparagus on a baking sheet.",
          "Drizzle with olive oil, lemon juice, and minced garlic.",
          "Season with salt and pepper.",
          "Bake for 20 minutes."
        ],
        time: "30 mins",
        difficulty: "Medium",
        calories: "400 cal"
      },
      {
        id: "15",
        name: "Veggie Stir-Fry",
        category: "Lunch",
        image: require("../assets/images/veggiestirfrybrownrice.jpg"),
        rating: 4.6,
        ingredients: ["Brown rice", "Broccoli", "Bell peppers", "Carrots", "Snap peas", "Soy sauce", "Ginger", "Garlic", "Olive oil"],
        description: "A colorful stir-fry with assorted vegetables and brown rice.",
        recipe: [
          "Cook brown rice according to package instructions.",
          "In a pan, sauté garlic and ginger in olive oil.",
          "Add vegetables and stir-fry until tender.",
          "Add soy sauce and serve over brown rice."
        ],
        time: "30 mins",
        difficulty: "Medium",
        calories: "350 cal"
      },
      {
        id: "16",
        name: "Spinach and Feta Stuffed Peppers",
        category: "Lunch",
        image: require("../assets/images/spinachfetastuffedpeppers.jpg"),
        rating: 4.7,
        ingredients: ["Bell peppers", "Spinach", "Feta cheese", "Quinoa", "Olive oil", "Garlic", "Salt", "Pepper"],
        description: "Bell peppers stuffed with a savory mixture of spinach and feta.",
        recipe: [
          "Preheat oven to 375°F (190°C).",
          "Sauté garlic and spinach in olive oil.",
          "Mix cooked quinoa and feta cheese with the spinach.",
          "Stuff the mixture into halved bell peppers.",
          "Bake for 25 minutes."
        ],
        time: "35 mins",
        difficulty: "Medium",
        calories: "300 cal"
      },
      {
        id: "17",
        name: "Grilled Salmon with Quinoa",
        category: "Dinner",
        image: require("../assets/images/grilledsalmonquinoa.jpg"),
        rating: 4.9,
        ingredients: ["Salmon fillet", "Quinoa", "Olive oil", "Lemon", "Garlic", "Salt", "Pepper", "Parsley"],
        description: "A heart-healthy dinner featuring grilled salmon and quinoa.",
        recipe: [
          "Season salmon with olive oil, lemon juice, garlic, salt, and pepper.",
          "Grill salmon until fully cooked.",
          "Cook quinoa according to package instructions.",
          "Serve grilled salmon over quinoa, garnished with chopped parsley."
        ],
        time: "30 mins",
        difficulty: "Medium",
        calories: "450 cal"
      },
      {
        id: "18",
        name: "Vegetable Stir-Fry with Tofu",
        category: "Dinner",
        image: require("../assets/images/vegetablestirfrytofu.jpg"),
        rating: 4.7,
        ingredients: ["Tofu", "Broccoli", "Carrots", "Bell peppers", "Snap peas", "Soy sauce", "Ginger", "Garlic", "Olive oil"],
        description: "A flavorful stir-fry with tofu and a mix of vegetables.",
        recipe: [
          "Press tofu to remove excess water, then cut into cubes.",
          "Sauté tofu in olive oil until golden brown.",
          "Add garlic and ginger, then stir-fry vegetables until tender.",
          "Add soy sauce and cook for a few more minutes."
        ],
        time: "25 mins",
        difficulty: "Easy",
        calories: "400 cal"
      },
      {
        id: "19",
        name: "Baked Cod with Veggies",
        category: "Dinner",
        image: require("../assets/images/bakedcodveggies.jpg"),
        rating: 4.8,
        ingredients: ["Cod fillet", "Cherry tomatoes", "Zucchini", "Olive oil", "Lemon", "Garlic", "Salt", "Pepper"],
        description: "A simple and nutritious meal with baked cod and vegetables.",
        recipe: [
          "Preheat oven to 375°F (190°C).",
          "Place cod fillets, cherry tomatoes, and sliced zucchini on a baking sheet.",
          "Drizzle with olive oil, lemon juice, and minced garlic.",
          "Season with salt and pepper, then bake for 20 minutes."
        ],
        time: "30 mins",
        difficulty: "Easy",
        calories: "350 cal"
      },
      {
        id: "20",
        name: "Chicken and Vegetable Skewers",
        category: "Dinner",
        image: require("../assets/images/chickenvegskewers.jpg"),
        rating: 4.8,
        ingredients: ["Chicken breast", "Bell peppers", "Zucchini", "Red onion", "Olive oil", "Lemon juice", "Salt", "Pepper"],
        description: "Colorful skewers with marinated chicken and fresh vegetables.",
        recipe: [
          "Cut chicken and vegetables into bite-sized pieces.",
          "Marinate chicken in olive oil, lemon juice, salt, and pepper.",
          "Thread chicken and vegetables onto skewers.",
          "Grill until chicken is cooked through and vegetables are tender."
        ],
        time: "25 mins",
        difficulty: "Medium",
        calories: "400 cal"
      },
      {
        id: "21",
        name: "Stuffed Bell Peppers",
        category: "Dinner",
        image: require("../assets/images/stuffedbellpeppers.jpg"),
        rating: 4.7,
        ingredients: ["Bell peppers", "Ground turkey", "Brown rice", "Tomato sauce", "Onion", "Garlic", "Salt", "Pepper"],
        description: "Bell peppers stuffed with a flavorful mixture of turkey and rice.",
        recipe: [
          "Preheat oven to 375°F (190°C).",
          "Sauté chopped onion and garlic, then add ground turkey and cook until browned.",
          "Mix in cooked brown rice and tomato sauce, season with salt and pepper.",
          "Stuff the mixture into halved bell peppers.",
          "Bake for 25 minutes."
        ],
        time: "40 mins",
        difficulty: "Medium",
        calories: "450 cal"
      },
      {
        id: "22",
        name: "Lentil and Vegetable Stew",
        category: "Dinner",
        image: require("../assets/images/lentilveggiestew.jpg"),
        rating: 4.6,
        ingredients: ["Lentils", "Carrots", "Celery", "Onion", "Garlic", "Tomato paste", "Vegetable broth", "Olive oil", "Salt", "Pepper", "Thyme"],
        description: "A hearty and comforting stew with lentils and vegetables.",
        recipe: [
          "Sauté chopped onions, carrots, celery, and garlic in olive oil.",
          "Add lentils, vegetable broth, tomato paste, salt, pepper, and thyme.",
          "Simmer until lentils and vegetables are tender."
        ],
        time: "45 mins",
        difficulty: "Medium",
        calories: "400 cal"
      },
      {
        id: "23",
        name: "Shrimp and Asparagus Stir-Fry",
        category: "Dinner",
        image: require("../assets/images/shrimpasparagusstirfry.jpg"),
        rating: 4.8,
        ingredients: ["Shrimp", "Asparagus", "Garlic", "Ginger", "Olive oil", "Soy sauce", "Lemon juice", "Salt", "Pepper"],
        description: "A quick and easy stir-fry with shrimp and asparagus.",
        recipe: [
          "Sauté garlic and ginger in olive oil.",
          "Add shrimp and cook until pink.",
          "Add asparagus and stir-fry until tender.",
          "Season with soy sauce, lemon juice, salt, and pepper."
        ],
        time: "20 mins",
        difficulty: "Easy",
        calories: "350 cal"
      },
      {
        id: "24",
        name: "Quinoa Stuffed Eggplant",
        category: "Dinner",
        image: require("../assets/images/quinoastuffedeggplant.jpg"),
        rating: 4.7,
        ingredients: ["Eggplant", "Quinoa", "Tomato", "Spinach", "Garlic", "Olive oil", "Feta cheese", "Salt", "Pepper"],
        description: "Eggplant halves stuffed with a savory quinoa and vegetable mix.",
        recipe: [
          "Preheat oven to 375°F (190°C).",
          "Halve and hollow out eggplants.",
          "Sauté garlic and spinach in olive oil.",
          "Mix cooked quinoa, diced tomato, and sautéed spinach.",
          "Stuff the mixture into eggplant halves, top with feta cheese.",
          "Bake for 25 minutes."
        ],
        time: "40 mins",
        difficulty: "Medium",
        calories: "350 cal"
      }    
];
export const Exercises =[
  {
    id: "01",
    ExerciseName: "Jump Rope",
    category: "Aerobic",
    ExerciseImage: require("../assets/images/ex2.jpg"),
    ExerciseDescription: "Sets:3     Reps:20     Rest: 1.5min",
    ExerciseTime: "5 mins",
    ExerciseDifficulty: "Moderate",
    ExerciseCalories: "15-24 cal",
    ExerciseInformation: ["1. Hold the rope while keeping your hands at hip level.",
    "2. Rotate your wrists to swing the rope and jump.",
    "3. Jump with both feet at the same time, one foot at a time, alternating between feet, etc.",
    "4. Repeat until the set is complete.",
    "Engage your abs, loosen your shoulders and turn the rope only with your wrists, not the entire arms. Keep the upper body straight, knees slightly bent, and jump on the balls of your feet. For a low-impact exercise, focus on doing faster and smaller jumps. Breathe deeply and naturally, keeping a smooth and steady rhythm."],
  },
  {
    id: "02",
    ExerciseName: "Squats",
    category: "Aerobic",
    ExerciseImage: require("../assets/images/ex3.jpg"),
            ExerciseDescription: ["Sets:3     Reps:10     Rest: 1min"],
            ExerciseTime: "4 mins",
            ExerciseDifficulty: "Moderate",
            ExerciseCalories: "7.5-10.5 cal",
            ExerciseInformation: ["1. Stand up with your feet shoulder-width apart.",
            "2. Bend your knees, press your hips back and stop the movement once the hip joint is slightly lower than the knees.",
            "3. Press your heels into the floor to return to the initial position.",
            "4. Repeat until the set is complete.",
            "When doing squats maintain your back in alignment, by keeping your chest up and your hips back. Don’t let the knees extend beyond the toes and put pressure on the heels of the feet. Breathe in as you squat and breathe out as you come up."],
        },
        {
            id: "03",
            ExerciseName: "Push Ups",
            category: "Aerobic",
            ExerciseImage: require("../assets/images/ex4.jpg"),
            ExerciseDescription: ["Sets:3     Reps:7     Rest: 1min"],
            ExerciseTime: "3.5 mins",
            ExerciseDifficulty: "Moderate",
            ExerciseCalories: "5-7 cal",
            ExerciseInformation: ["1. With your legs extended back, place the hands below the shoulders, slightly wider than shoulder-width apart.",
            "2. Start bending your elbows and lower your chest until it’s just above the floor.",
            "3. Push back to the starting position. A 1-second push, 1-second pause, 2-second down count is ideal.",
            "4. Repeat until the set is complete.",
            "While doing the push-up exercise focus on keeping your head in line with your torso, and your torso in line with your hips. Engage your core muscles, maintain your body in a straight line, and exhale as you push back. Take the pressure off the wrists and place it on the outside of your hands."],    
        },
        {
            id: "04",
            ExerciseName: "Triceps Dips",
            category: "Aerobic",
            ExerciseImage: require("../assets/images/ex5.png"),
            ExerciseDescription: "Sets:3     Reps:10     Rest: 1min",
            ExerciseTime: "4 mins",
            ExerciseDifficulty: "Moderate",
            ExerciseCalories: "7.5-10.5 cal",
            ExerciseInformation: ["1. Place your hands behind you onto a chair, so that your fingers face forward.",
            "2. Extend your legs and start bending your elbows.",
            "3. Lower your body until your arms are at a 90-degree angle.",
            "4. Lift your body back up until your arms are straight.",
            "5. Repeat",
            "When doing tricep dips roll your shoulders back, open the chest, keep your neck nice and tall and place your hands underneath your shoulders. Inhale as you bend your elbows and breathe out as you extend the elbows and lift yourself back up."],
          },
          {
            id: "05",
            ExerciseName: "Torso Twist",
            category: "Aerobic",
            ExerciseImage: require("../assets/images/ex6.png"),
            ExerciseDescription: "Sets:3     Reps:15     Rest: 1.5min",
            ExerciseTime: "5.5 mins",
            ExerciseDifficulty: "Moderate",
            ExerciseCalories: "6.7-11.2 cal",
            ExerciseInformation: ["1. With your legs extended back, place the hands below the shoulders, slightly wider than shoulder-width apart.",
            "2. Start bending your elbows and lower your chest until it’s just above the floor.",
            "3. Push back to the starting position. A 1-second push, 1-second pause, 2-second down count is ideal.",
            "4. Repeat until the set is complete.",
            "While doing the push-up exercise focus on keeping your head in line with your torso, and your torso in line with your hips. Engage your core muscles, maintain your body in a straight line, and exhale as you push back. Take the pressure off the wrists and place it on the outside of your hands."],
          },
          {
            id: "06",
            ExerciseName: "Lunges",
            category: "Aerobic",
            ExerciseImage: require("../assets/images/ex7.jpg"),
            ExerciseDescription: "Sets:3     Reps:18     Rest: 1min",
            ExerciseTime: "4.7 mins",
            ExerciseDifficulty: "Moderate",
            ExerciseCalories: "13.5-18.9 cal",
            ExerciseInformation: ["1. Stand with your feet hip-width apart, keep your back straight, your shoulders back, and your abs tight.",
            "2. Take a step forward and slowly bend both knees, until your back knee is just above the floor.",
            "3. Stand back up and repeat the movement",
            "4. Alternate legs until the set is complete.",
            "When doing lunges, keep your weight in the front heel and make sure that when you’re bending your front knee, your thigh and leg form a 90-degree angle. Maintain your feet hip-width apart throughout the entire exercise, don’t put one foot in front of the other. Breathe in as you lunge, and maintain a smooth and steady rhythm."],
          },
          {
                    id: "07",
                    ExerciseName: "Seated Marching",
                    category: "Gait",
                    ExerciseImage: require("../assets/images/seatmarching.jpg"),
                    ExerciseDescription: ["Sets:3     Reps:20     Rest: 30sec"],
                    ExerciseTime: "3 mins",
                    ExerciseDifficulty: "Low",
                    ExerciseCalories: "4-6 cal",
                    ExerciseInformation: ["1. Sit comfortably in a chair and lift one knee up toward the ceiling. ",
                    "2. Reach your knee as high as is comfortable and hold this position for a few moments",
                    "3. Relax your foot back to the floor.",
                    "4. Repeat",
                    "As you do each rep, you might feel your core and hip muscles working. Everyone is different, which is why you may need to modify this exercise to meet your needs."],
                },
                {
                    id: "08",
                    ExerciseName: "Knee Extension",
                    category: "Gait",
                    ExerciseImage: require("../assets/images/kneeextension.jpg"),
                    ExerciseDescription: ["Sets:3     Reps:20     Rest: 30sec"],
                    ExerciseTime: "4 mins",
                    ExerciseDifficulty: "Low",
                    ExerciseCalories: "9-15 cal",
                    ExerciseInformation: ["1. Sitting up tall with your shoulders back and down.",
                    "2. Lifting one leg up, extending at the knee.",
                    "3. Hold briefly at the top of the movement, squeezing the muscles at the front of the thigh before lowering your leg back down.",
                    "4. Ensure the movement is slow and controlled.",
                    "5. Alternate legs, ensuring full knee extension (leg completely straight).",
                    "6. Repeat for the set repetitions.",
                    "As you do each rep, you might feel your leg muscles working. Everyone is different, which is why you may need to modify this exercise to meet your needs."],
                },
                {
                    id: "09",
                    ExerciseName: "Side Leg Raises",
                    category: "Gait",
                    ExerciseImage: require("../assets/images/sidelegraises.jpg"),
                    ExerciseDescription: ["Sets:3     Reps:15     Rest: 1min"],
                    ExerciseTime: "4.5 mins",
                    ExerciseDifficulty: "Moderate",
                    ExerciseCalories: "6.5-11.5 cal",
                    ExerciseInformation: ["1. Lie on your side with your legs fully extended and stacked.",
                    "2. Lift both legs, keeping the feet together, and pause for 2 seconds.",
                    "3. Lower the legs, repeat, then switch sides.",
                    "Tighten the core, keep your upper body stable and breathe out as you lift the legs. Engage your hips and glutes and breathe in as you lower the legs back to the starting position."],
                },
                {
                    id: "10",
                    ExerciseName: "Toe Taps",
                    category: "Gait",
                    ExerciseImage: require("../assets/images/toetaps.jpg"),
                    ExerciseDescription: ["Sets:3     Reps:20     Rest: 1min"],
                    ExerciseTime: "4 mins",
                    ExerciseDifficulty: "Low",
                    ExerciseCalories: "6-10 cal",
                    ExerciseInformation: ["1. Lay on your back and bring your knees up in the air.",
                    "2. Hold them at a 90 degree angle (table top position).",
                    "3. Keep them at 90 degree angle the whole time.",
                    "4. Slowly lower your feet down to the ground.",
                    "5. Lightly touch the floor and then bring them back up to table top position.",
                    "6. Repeat for the set repetitions.",
                    "Toe tap is a calisthenics and pilates exercise that primarily targets the abs and to a lesser degree also targets the groin, hip flexors, lower back and quads."],
                },
                {
                    id: "11",
                    ExerciseName: "Knee to Chest",
                    category: "Gait",
                    ExerciseImage: require("../assets/images/kneetochest.jpg"),
                    ExerciseDescription: ["Sets:3     Reps:20     Rest: 1min"],
                    ExerciseTime: "4 mins",
                    ExerciseDifficulty: "Low",
                    ExerciseCalories: "6-10 cal",
                    ExerciseInformation: ["1. Lie down on your back and pull both knees up to your chest.",
                    "2. Slowly pull the knees toward the shoulders until you feel the stretch in your lower back.",
                    "3. Stay in knees to chest pose for 30 seconds to 1 minute",
                    "Lift both legs, clasp your hands around the knees, and, as you exhale, tighten the grip. As you inhale, loosen the grip and relax. Breathe smoothly, keep your back flat on the mat and lengthen the spine."],
                },
                {
                    id: "12",
                    ExerciseName: "Ankle Dorsiflexion",
                    category: "Gait",
                    ExerciseImage: require("../assets/images/ex1.png"),
                    ExerciseDescription: ["Sets:3     Reps:10     Rest: 1.5min"],
                    ExerciseTime: "4 mins",
                    ExerciseDifficulty: "Low",
                    ExerciseCalories: "2-3 cal",
                    ExerciseInformation: ["1. Sit on the floor or on a chair with your back straight. If seated on the floor, extend your legs out in front of you.",
                    "2. Keep your leg extended and your heel on the ground",
                    "3. Loop a resistance band around the ball of your foot. Hold the ends of the band firmly to create tension.",
                    "4. Slowly pull your foot upwards against the resistance of the band. This adds difficulty and helps strengthen the muscles involved in dorsiflexion.",
                    "5. Hold the dorsiflexed position for a few seconds then slowly return to the starting position, controlling the movement against the band's resistance.",
                    "Focus on slow and controlled movements to avoid injury and maximize muscle engagement. Breathe normally throughout the exercise. Avoid holding your breath. Maintain a straight back and avoid slouching, especially if you're seated. Incorporate ankle dorsiflexion exercises into your regular fitness routine for best results."],
                },
                {
                          id: "13",
                          ExerciseName: "Bicep Curls",
                          category: "Strength",
                          ExerciseImage: require("../assets/images/b1.jpg"),
                          ExerciseDescription: "Sets:3     Reps:13     Rest: 15sec",
                          ExerciseTime: "2 mins",
                          ExerciseDifficulty: "Difficult",
                          ExerciseCalories: "7-15 cal",
                          ExerciseInformation: ["1. Stand straight with a dumbbell in each hand, your feet shoulder-width apart, and hands by your sides.",
                          "2. Squeeze the biceps and lift the dumbbells. Keep the elbows close to your body and the upper arms stationary, only the forearms should move.",
                          "3. Once the dumbbells are at shoulder level, slowly lower the arms to the starting position.",
                          "4. Repeat.",
                          "While doing bicep curls keep your knees and elbow joints loose, engage your core muscles and keep your palms facing front. Breathe out as you lift the dumbbells and maintain your back straight, your shoulders back and your head up."],
                        },
                        {
                          id: "14",
                          ExerciseName: "Sit-to-stand",
                          category: "Strength",
                          ExerciseImage: require("../assets/images/b2.jpg"),
                          ExerciseDescription: "Sets:3     Reps:20     Rest: 25sec",
                          ExerciseTime: "5 min",
                          ExerciseDifficulty: "Difficult",
                          ExerciseCalories: "17-34 cal",
                          ExerciseInformation: ["1. Sit toward the front edge of a sturdy chair without armrests. Your knees should be bent and your feet should be flat on the floor and shoulder-width apart and underneath your hips.",
                          "2. Place your hands lightly on each side of the seat. Keep your back and neck as straight as possible, with your chest slightly forward.",
                          "3. Breathe in slowly. Lean forward and slightly shift your weight to the front of your feet.",
                          "4. Breathe out as you slowly stand up. Try not to support any weight with your hands.",
                          "5. Stand and pause for a full breath in and out.",
                          "6. Repeat.",
                          "Breathe in as you sit down slowly. Tighten your core and abdominal muscles to control your lowering as much as possible. You should lower yourself back to the chair slowly, not just drop back into the seat."],
                        },
                        {
                          id: "15",
                          ExerciseName: "Deadlift",
                          category: "Strength",
                          ExerciseImage: require("../assets/images/b3.jpg"),
                          ExerciseDescription: "Sets:3     Reps:7     Rest: 1min",
                          ExerciseTime: "3 mins",
                          ExerciseDifficulty: "Difficult",
                          ExerciseCalories: "7-17 cal",
                          ExerciseInformation: ["1. Stand with your mid-foot under the barbell.",
                          "2. Bend over and grab the bar with a shoulder-width grip.",
                          "3. Bend your knees until your shins touch the bar.",
                          "4. Lift your chest up and straighten your lower back.",
                          "5. Take a big breath, hold it, and stand up with the weight",
                          "6. Repeat",
                          "Hold the weight for a second at the top, with locked hips and knees. Then return the weight to the floor by moving your hips back while bending your legs. Rest a second at the bottom and repeat."],
                        },
                        {
                          id: "16",
                          ExerciseName: "Glute Bridge",
                          category: "Strength",
                          ExerciseImage: require("../assets/images/b4.jpg"),
                          ExerciseDescription: "Sets:3     Reps:13     Rest: 1min",
                          ExerciseTime: "5 mins",
                          ExerciseDifficulty: "Difficult",
                          ExerciseCalories: "30-50 cal",
                          ExerciseInformation: ["1. Lie on your back with your hands by your sides and your knees bent.",
                          "2. Lift your hips off the mat, while keeping your back straight, and pause for 1 second.",
                          "3. Return to the starting position and repeat the movement until the set is complete.",
                          "4. Repeat",
                          "When doing the glute bridge, press down through the heels to lift your hips and keep your core and glutes tight. Maintain the upper body relaxed and keep the knees bent at a 45-degree angle. Exhale as you lift your butt off the floor and inhale as you return to the starting position."],
                        },
                        {
                          id: "17",
                          ExerciseName: "Bent-Over Row",
                          category: "Strength",
                          ExerciseImage: require("../assets/images/b5.png"),
                          ExerciseDescription: "Sets:3     Reps:10    Rest: 1min",
                          ExerciseTime: "6 mins",
                          ExerciseDifficulty: "High Difficulty",
                          ExerciseCalories: "20-30 cal",
                          ExerciseInformation: ["1. Grab a set of dumbbells, bend your torso forward and keep your knees slightly bent.",
                          "2. Pull the dumbbells toward your waistline, while squeezing your shoulder blades.",
                          "3. Slowly lower the weights to the starting position. A 1-second pull, 1-second pause, 2 second down count is ideal.",
                          "4. Repeat",
                          "While doing the dumbbell bent over row, pull the shoulders back, keep your head up and facing forward and maintain your back straight. Exhale as you pull the dumbbells toward the waist and keep the elbows close to your body during the entire movement."],
                        },
                        {
                          id: "18",
                          ExerciseName: "Stair climbers",
                          category: "Aerobic",
                          ExerciseImage: require("../assets/images/b6.jpg"),
                          ExerciseDescription: "Sets:3     Reps:20     Rest: 30sec",
                          ExerciseTime: "11 mins",
                          ExerciseDifficulty: "Moderate",
                          ExerciseCalories: "50-70 cal",
                          ExerciseInformation: ["1. Rest your hands — or better yet, your fingertips — lightly on the bar in front of you or on the side rails.",
                          "2. Stand upright with a slight forward lean at the hips.",
                          "3. Take even, moderately deep steps.",
                          "4. Repeat",
                          "Don’t take short, quick hopping steps, a technique known as shaking the machine. This technique is hard on your calf muscles and cuts down on the number of calories you burn."],
                        },
                        {
                          id: "19",
                          ExerciseName: "Arm circles",
                          category: "Aerobic",
                          ExerciseImage: require("../assets/images/b7.jpg"),
                          ExerciseDescription: "Sets:3     Reps:10     Rest: 1min",
                          ExerciseTime: "5 mins",
                          ExerciseDifficulty: "Low",
                          ExerciseCalories: "10-15 cal",
                          ExerciseInformation: ["1. Stand straight with your feet shoulder-width apart.",
                          "2. Raise and extend your arms to the sides without bending the elbows.",
                          "3. Slowly rotate your arms forward, making small circles of about 1 foot in diameter.",
                          "4. Complete a set in one direction and then switch, rotating backward.",
                          "5. Repeat",
                          "While doing arm circles engage your core muscles, keep your back and your arms straight and maintain a smooth and deep breathing pattern. Keep your head up and your body in a T formation during the entire exercise."],
                        },
                        {
                          id: "20",
                          ExerciseName: "Jumping jacks",
                          category: "Aerobic",
                          ExerciseImage: require("../assets/images/b8.jpg"),
                          ExerciseDescription: "Sets:3     Reps:10     Rest: 30sec",
                          ExerciseTime: "3.5 mins",
                          ExerciseDifficulty: "Moderate",
                          ExerciseCalories: "20-30 cal",
                          ExerciseInformation: ["1. Stand straight with your feet together and hands by your sides.",
                          "2. Jump up, spread your feet and bring both hands together above your head.",
                          "3. Jump again and return to the starting position.",
                          "4. Repeat until the set is complete.",
                          "Keep the knees slightly bent and land softly on the balls of your feet. Engage your core and glutes and maintain your knees in line with your hips and feet. Keep your arms extended and your elbows loose during the entire exercise and maintain a steady and smooth breathing pattern."],
                        },
                        {
                          id: "21",
                          ExerciseName: "Mountain climbers",
                          category: "Aerobic",
                          ExerciseImage: require("../assets/images/b9.png"),
                          ExerciseDescription: "Sets:3     Reps:13     Rest: 1min",
                          ExerciseTime: "4.25 mins",
                          ExerciseDifficulty: "Moderate",
                          ExerciseCalories: "25-35 cal",
                          ExerciseInformation: ["1. Start with your body in a straight line and your hands slightly wider than shoulder-width apart. Keep your toes and balls of the feet touching the floor.",
                          "2. Bring one knee up toward the center of your stomach and then quickly alternate between legs.",
                          "3. Continue alternating until the set is complete.",
                          "Maintain a plank position during the entire exercise, keep your core engaged, your hips low and your body in a straight line. It’s important to maintain proper alignment to get the most out of the exercise. Don’t sacrifice the form for the speed and try to breathe as slowly as possible."],
                        },
                        {
                          id: "22",
                          ExerciseName: "Calf Stretches",
                          category: "Gait",
                          ExerciseImage: require("../assets/images/b11.png"),
                          ExerciseDescription: "Sets:3     Reps:13     Rest: 1min",
                          ExerciseTime: "3.25 mins",
                          ExerciseDifficulty: "Low",
                          ExerciseCalories: "1-5 cal",
                          ExerciseInformation: ["1. Stand holding onto a wall with your arms extended and your toes pointing forward.",
                          "2. Extend your right leg back, keeping your right foot flat on the floor.",
                          "3. Lean forward and slowly bend your left knee until you feel the stretch in your back calf.Continue alternating until the set is complete.",
                          "4. Hold the stretch and repeat on the left leg.",
                          "Keep both feet facing forward and push the rear heel down into the floor. Keep your back knee straight and drop your hips down and forward. As you exhale, ease further into the stretch without forcing it."],
                        },
                        {
                          id: "23",
                          ExerciseName: "Hip Flexor Stretches",
                          category: "Gait",
                          ExerciseImage: require("../assets/images/b12.png"),
                          ExerciseDescription: "Sets:3     Reps:13     Rest: 30sec",
                          ExerciseTime: "3 mins",
                          ExerciseDifficulty: "Low",
                          ExerciseCalories: "1-5 cal",
                          ExerciseInformation: ["1. Kneel on your right leg and bend your left leg in front of you at a 90-degree angle.",
                          "2. Shift your weight forward until you feel a stretch in your hip.",
                          "3. Switch legs and repeat the stretch.",
                          "While doing the hip flexor stretch keep your back in a neutral position and face forward. Breathe in through your nose and, as you breathe out through your mouth, try to deepen the stretch. Don’t let your front knee go past your toes and only go as far as it feels comfortable to you."],
                        },
  
]